Neos:
  Neos:
    modules:
      administration:
        submodules:
          nodetypes:
            label: 'Shel.ContentRepository.Debugger:Main:module.label'
            controller: 'Shel\ContentRepository\Debugger\Controller\NodeTypesController'
            description: 'Shel.ContentRepository.Debugger:Main:module.description'
            icon: 'fas fa-sitemap'
            privilegeTarget: 'Shel.ContentRepository.Debugger:Backend.Module.Administration.NodeTypes'
            additionalResources:
              javaScripts:
                - 'resource://Shel.ContentRepository.Debugger/Public/Assets/main.bundle.js'
              styleSheets:
                - 'resource://Shel.ContentRepository.Debugger/Public/Assets/extra-neos-wrapper.css'

    userInterface:
      translation:
        autoInclude:
          Shel.ContentRepository.Debugger:
            - 'Main'
